esphome:
  name: tuya_test
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret SSID
  password: !secret pass_SSID
  fast_connect: true
#  manual_ip:
#    static_ip: 192.168.1.137
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0



# Enable logging
logger:

api:
ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: Tuya test Wifi Signal
    update_interval: 10s
  - platform: uptime
    name: Tuya test Uptime

binary_sensor:
  - platform: status
    name: Tuya test Status
    
  - platform: gpio
    pin:
      number: GPIO12
      #mode: INPUT_PULLUP
      inverted: True
    name: "Switch"
    on_state:
      - light.toggle: lightid
    internal: true


output:
  - platform: gpio
    pin: GPIO13
    id: gpio_13
    
light:
  - platform: binary
    name: "lampara"
    output: gpio_13
    id: lightid


